### ISSUE TITLE
LoadBalancer service deletion does not assign IP to existing claims

### ISSUE THREAD

**Issue by anandsinghkunwar** [danderson/metallb#321]
**Is this a bug report or a feature request?**:
Bug Report

**What happened**:
I tried creating two services with the same fixed `loadBalancerIP`, one of them gets the allocated IP, the other one doesn't. This is the expected behavior.  
However, when I delete the first service, I expect the second service to get the IP assigned which does not happen. 
You may ask what exact scenario does justify having two services with the same IP. I have a scenario where this might be justified. Suppose you have a helm chart with a service with a fixed `loadBalancerIP`. Now some refactoring later, this service has a name change. Due to `helm upgrade` magic, you may have both services momentarily with the same `loadBalancerIP`, due to which the service with the newer name never gets the IP assigned to it.   

**What you expected to happen**:
I expect the second service to get the IP assigned when the first service is deleted that does not happen.

**How to reproduce it (as minimally and precisely as possible)**:
This is the minimal set of services to illustrate this problem:
```
kind: Service
apiVersion: v1
metadata:
  name: myip-service-fixed-ip
spec:
  selector:
    app: myip
  type: LoadBalancer
  loadBalancerIP: 10.10.17.20
  ports:
  - name: http
    port: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: myip-service-fixed-ip2
spec:
  selector:
    app: myip
  type: LoadBalancer
  loadBalancerIP: 10.10.17.20
  ports:
  - name: http
    port: 8080
```

**Anything else we need to know?**:
MetalLB runs in L2 mode in our setup.

**Environment**:
- MetalLB version: `0.7.2`
- Kubernetes version: `1.10.3`
- BGP router type/version: NA
- OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): `3.10.0-693.el7.x86_64`
