### ISSUE TITLE
metallb match between ip range to service by location

### ISSUE THREAD

**Issue by dorsany** [danderson/metallb#389]
**Is this a bug report or a feature request?**:
feature request

**What happened**:
I have on premise kubernetes cluster  with many nodes in multy regions, which means several ip networks.
For example, I have worker1 in New-York with subnet of 192.168.1.0/24 and worker2 in Los Angeles  with subnet of 10.0.0.0/24
from some reason the metallb assign to my services in New-York ip from the ip range in Los Angeles

**What you expected to happen**:
because metallb is working on layer 2, I was expected that the metallb will assign the relevant ip to each region by check the subnet of the network
or
a way to match between a service to a specific range of IPs in the metallb

**How to reproduce it (as minimally and precisely as possible)**:
craete worker1 and config the metallb to a different range of ips.
the metallb will assign this range even the worker1 is not familiar with this ip

**Anything else we need to know?**:

my worker ip address: 192.168.1.200

config file:
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: my-ip-space
      protocol: layer2
      addresses:
      - 10.0.0.1-10.0.0.2
```
nginx:
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1
        ports:
        - name: http
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
```
kubectl get svc

```
NAME         TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP      10.96.0.1      <none>        443/TCP        11d
nginx        LoadBalancer   10.107.108.1   10.0.0.1      80:32590/TCP   3h27m

```

**Environment**:
- MetalLB version: 0.73
- Kubernetes version: 1.12.4
- BGP router type/version: none
- OS (e.g. from /etc/os-release): ubuntu 18.04
- Kernel (e.g. `uname -a`): 4.15.0-43-generic
