### ISSUE TITLE
Layer2 mode on Minikube works for exactly 1 service

### ISSUE THREAD

**Issue by afritzler** [danderson/metallb#418]
Hi,

I am having trouble exposing more than one LB service via metal-lb layer2 mode in a Minikube environment.

I am running Minikube on MacOS via Hyperkit. Here is my configration of metal-lb

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: custom-ip-space
      protocol: layer2
      addresses:
      - 192.168.99.14-192.168.99.20 # .14 is the address of my minikube box
```

The first service now gets the IP 192.168.99.14 and is accessible from the my host. The second service is assigned 192.168.99.15 but is not accessible. The `speaker` is advertising the .15 address correctly to the host because it is showing up via `netstat -rn`.

Am I missing something?

Regards,
Andraes
