### ISSUE TITLE
Support per node ip pool when using MetalLB in L2

### ISSUE THREAD

**Issue by AlexisDucastel** [danderson/metallb#432]
This is a feature request.

When working with low cost dedicated server solution, you can rent a server with a public ip. You can most of the time order a bunch of other IP that will be routed directly on your server. (Ex: OVH, a french hosting provider). 

If you rent multiple servers, you will then get group of ip pools, but each pool is only usable by one server at all.

The feature would be to add a NodeSelector on a L2 pool, to let the specific node receiving this pool answer to ARP requests.

A possible configuration could be very close to BGP peer affinity : 
```
address-pools:
- addresses:
  - 176.31.76.164/30
  name: default
  protocol: layer2
  node-selectors:
  - match-labels:
      rack: frontend
    match-expressions:
    - key: network-speed
      operator: NotIn
      values: [slow]
  - match-expressions:
    - key: kubernetes.io/hostname
      operator: In
      values: [hostA, hostB]
```

This would be awesome.
