### ISSUE TITLE
NodeSelector option for use specific config for specific node for MetalLB

### ISSUE THREAD

**Issue by Diz100rM** [danderson/metallb#442]
I have a k8s cluster with 4 nodes and i have a need to announce a public IP for services in cluster by BGP

For example i have 4 configs, with AS number and IP's for anouncment for each node
```
peers:
- my-asn: 65000
  peer-asn: 65000
  peer-address: 1.1.1.1
- my-asn: 65001
  peer-asn: 65000
  peer-address: 2.2.2.2
```

I'm using `node-selector` for configure which node need to use a need config, but it's doesn't work. What im doing wrong?

So after `node-selectors` it's looks like this:

```
peers:
- my-asn: 65001
  peer-asn: 65000
  peer-address: 1.1.1.1
- my-asn: 65002
  peer-asn: 65000
  peer-address: 2.2.2.2
  node-selectors:
  - match-expressions:
     - key: kubernetes.io/hostname
       operator: In
       values: [Node1]
- my-asn: 65003
  peer-asn: 65000
  peer-address: 3.3.3.3
- my-asn: 65004
  peer-asn: 65000
  peer-address: 4.4.4.4
  node-selectors:
  - match-expressions:
     - key: kubernetes.io/hostname
       operator: In
       values: [Node2]
```

But it's also doesn't work for me

**Comment by Diz100rM** [comment]
Solved by using this config structure :

```
    peers:
    - my-asn: 65002
      peer-asn: 65000
      peer-address:  2.2.2.2
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [Node1]
    - my-asn: 65001
      peer-asn: 65000
      peer-address: 1.1.1.1
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [Node1]
```
