### ISSUE TITLE
"no available IPs/IP allocation failed" whatever range I set

### ISSUE THREAD

**Issue by mimmus** [danderson/metallb#487]
I just installed metallb by Helm chart and configured with this ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: metallb-config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.57.1.128/29`
```
I tried also with 10.57.1.128-10.57.1.131 and other ranges.
But when I expose a Service using LoadBalancer I get always:
_"error":"no available IPs","msg":"IP allocation failed"_

Where am I wrong?

Thanks

**Comment by Elegant996** [comment]
Does the Helm chart work with `inlineConfig`? Are the pods running correctly? Let's start small :)

```
configInline:
  address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.57.1.128/29
```

**Comment by mimmus** [comment]
It works :-)
If someone can explain me why...

Thanks

**Comment by Elegant996** [comment]
Please remember to close your issue if it is resolved. Thanks!

**Comment by mimmus** [comment]
There are a lot of bugs in documentation...

**Comment by danderson** [comment]
There aren't, the two configs you posted are semantically equivalent. I hope you enjoy the results of our free labor regardless, and I'm happy you fixed whatever the actual problem was!

**Comment by CSRedRat** [comment]
I had the same problem, when I use helm chart: https://github.com/bitnami/charts/tree/master/bitnami/metallb
In helm install need change namespace and name:

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: metallb
data:
  config: |
      address-pools:
      - addresses:
        - 192.168.1.100-192.168.88.110
        name: default
        protocol: layer2
```

MetalLB Helm chart, installed from Rancher Docker Apps - not working.

Can you log message if haven't ConfigMap with instructions for cofniguration?
